# docker-compose.path.yml
version: '3.8'

services:
  reverse-proxy:
    image: nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/path.conf:/etc/nginx/nginx.conf
    networks:
      - web

networks:
  web:
    driver: bridge
