services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles: ["path-based", "subdomain"]

  komet:
    image: ikebox/komet:0.0.1
    container_name: komet
    volumes:
      - ~/Solor:/root/Solor
      - ./komet-data/users.ini:/root/Solor/users.ini:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/status/alive || wget --spider -q http://localhost:8080/status/alive || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles: ["path-based", "subdomain"]

  nginx:
    build:
      context: .
    container_name: nginx
    # environment:
    #   - CERTBOT_HOST="localhost,www.ikedesigns.com,komet.ikedesigns.com,nexus.ikedesigns.com"
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - nexus
      - komet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NGINX_PORT:-80}/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles: ["path-based"]
  ikmdev-site:
      image: ikebox/ikmdev-site:1.0.0
      container_name: ikmdev-site
      volumes:
      - ikmdev-data:/data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/"]
        interval: 30s
        timeout: 10s
        retries: 3
      networks:
      - rapidenv
      restart: unless-stopped
      logging:
       driver: "json-file"
       options:
        max-size: "10m"
        max-file: "3"
      profiles: ["subdomain"]
  
  nginx-subdomain:
    build:
      context: .
      dockerfile: Dockerfile-subdomain-web
    container_name: nginx-subdomain
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT:-443}:443"
    volumes:
      - ./subdomain/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - nexus
      - komet
      - ikmdev-site
    healthcheck:
      test: ["CMD", "curl", "-f", "http://www.ikedesigns.com"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rapidenv
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles: ["subdomain"]
  certbot:
    image: certbot/certbot
    container_name: certbot
    environment: 
      - CERTBOT_HOST=*.ikedesigns.com"
    volumes:
      - certbot-data:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot --email admin@example.com --agree-tos --no-eff-email --staging -d ${CERTBOT_HOST} --non-interactive --keep-until-expiring; sleep 30d & wait $${!}; done;'"
    networks:
      - rapidenv
    restart: always
volumes:
  nexus-data:
  komet-data:
  nginx-logs:
  ikmdev-data:
  certbot-data:
  certbot-webroot:

networks:
  rapidenv:
    driver: bridge