services:
  dns-management:
    build:
      context: ./dns-management
      dockerfile: Dockerfile
    container_name: dns-management
    volumes:
      - ./dns-management/config.json:/app/config.json
      - ./dns-management/domains.txt:/app/domains.txt
    networks:
      - rapidenv
    restart: "no"
