FROM hashicorp/terraform:1.12.2
# This Dockerfile is used to set up a Terraform environment for AWS DNS management.

WORKDIR /aws-terraform

ENTRYPOINT ["/bin/sh", "-c", "terraform init && terraform plan"]

# Copy entryscript
COPY aws-terraform-entryscript.sh /aws-terraform-entryscript.sh
RUN chmod +x /aws-terraform-entryscript.sh

# Set entrypoint
ENTRYPOINT ["/aws-terraform-entryscript.sh"]

