FROM scalr/opentofu:1.9.2
# This Dockerfile is used to set up an environment for AWS DNS management.

WORKDIR /aws-terraform
# Install necessary packages  envsubst (provided by the gettext package)

RUN apt-get update && apt-get install -y gettext-base

# Copy Terraform configuration files
COPY ./dns-management/aws-domain-registration/infra /aws-infra

# Copy entryscript
COPY ./dns-management/aws-domain-registration/aws-entryscript.sh /aws-entryscript.sh
RUN chmod +x /aws-entryscript.sh

# Set entrypoint
ENTRYPOINT ["/aws-entryscript.sh"]

