name: Build and Publish ikebox infrastructure

on:
  workflow_dispatch:
  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
           docker compose -f docker-compose.yml build
           docker compose -f docker-compose.yml push

      - name: Deploy with Docker Compose
        run: |
            docker-compose -f docker-compose.yml up -d
  




 
