name: Build and Publish ikebox infrastructure

on:
  workflow_dispatch:
  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push nexus Image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/nexus:${{ github.ref_name }} .
         docker push ${{ secrets.DOCKER_USERNAME }}/nexus:${{ github.ref_name }}

      - name: Build and push gitea Image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/gitea:${{ github.ref_name }} .
         docker push ${{ secrets.DOCKER_USERNAME }}/gitea:${{ github.ref_name }}


      - name: Build and push nginx Image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.ref_name }} .
         docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.ref_name }}





      




 
